export const myPet = {
  id: 'hoshi',
  name: 'Hoshi',
  breed: 'Shih Tzu',
  species: 'Perro',
  age: 2,
  size: 'Pequeño',
  sex: 'Macho',
  energy: 'Activo',
  goodWith: 'Perros y personas',
  purpose: 'Amigos',
  location: 'Bethania, Ciudad de Panamá',
  emoji: '🐕',
  about: 'Le encanta jugar en el Parque Omar y conocer perros de su raza. ¡Curioso y amigable! 🐾',
  posts: 48,
  followers: 312,
  matches: 14,
}

export const stories = [
  { id: 1, name: 'Hoshi', emoji: '🐕',  color: '#7C3AED', bg: '#EDE9FE', mine: true },
  { id: 2, name: 'Rocky', emoji: '🐕‍🦺', color: '#0F9B8E', bg: '#E0F7F4' },
  { id: 3, name: 'Luna',  emoji: '🐩',  color: '#EC4899', bg: '#FCE7F3' },
  { id: 4, name: 'Simba', emoji: '🦊',  color: '#7C3AED', bg: '#EDE9FE' },
  { id: 5, name: 'Coco',  emoji: '🦮',  color: '#D97706', bg: '#FEF3C7' },
]

export const posts = [
  {
    id: 1,
    user: 'hoshi_oficial',
    petName: 'Hoshi 🐾',
    breed: 'Shih Tzu',
    time: 'hace 2 min',
    emoji: '🐕',
    avatarBg: '#EDE9FE',
    imgBg: '#EDE9FE',
    likes: 128,
    comments: 24,
    caption: '¡Qué lindo día en el Parque Omar! ¿Quién se apunta para el próximo paseo? 🐕',
    hashtags: '#PetSocial #ShihTzuPanama',
    liked: true,
  },
  {
    id: 2,
    user: 'rocky_bordercollie',
    petName: 'Rocky BC',
    breed: 'Border Collie',
    time: 'hace 45 min',
    emoji: '🐕‍🦺',
    avatarBg: '#E0F7F4',
    imgBg: '#E0F7F4',
    likes: 86,
    comments: 12,
    caption: 'Entrenando saltos en Costa del Este 🏃',
    hashtags: '#BorderColliePTY #PetSocial',
    liked: false,
  },
  {
    id: 3,
    user: 'luna_golden',
    petName: 'Luna ✨',
    breed: 'Golden Retriever',
    time: 'hace 1 hora',
    emoji: '🐩',
    avatarBg: '#FCE7F3',
    imgBg: '#FEF3C7',
    likes: 204,
    comments: 31,
    caption: 'Primer baño en PetGrooming PTY y quedé hermosa 💅',
    hashtags: '#GoldenRetrieverPTY #PetSocial #Grooming',
    liked: false,
  },
]

export const discoverPets = [
  {
    id: 1, name: 'Rocky', sex: 'Macho', age: 2,
    breed: 'Border Collie', species: 'Perro', size: 'Mediano',
    energy: 'Muy activo', purpose: 'Amigos',
    tags: ['Muy activo', 'Sociable', 'Busca amigos'],
    emoji: '🐕‍🦺', distance: 2.4, online: true,
    bg: '#E0F7F4', location: 'Costa del Este',
  },
  {
    id: 2, name: 'Luna', sex: 'Hembra', age: 3,
    breed: 'Golden Retriever', species: 'Perro', size: 'Grande',
    energy: 'Activa', purpose: 'Amigos',
    tags: ['Activa', 'Amigable', 'Busca amigos'],
    emoji: '🐩', distance: 2.1, online: false,
    bg: '#FEF3C7', location: 'San Francisco',
  },
  {
    id: 3, name: 'Simba', sex: 'Macho', age: 1,
    breed: 'Shiba Inu', species: 'Perro', size: 'Mediano',
    energy: 'Hiperactivo', purpose: 'Amigos',
    tags: ['Hiperactivo', 'Juguetón', 'Shiba Inu'],
    emoji: '🦊', distance: 1.8, online: true,
    bg: '#FEE2E2', location: 'Bella Vista',
  },
  {
    id: 4, name: 'Coco', sex: 'Hembra', age: 4,
    breed: 'Beagle', species: 'Perro', size: 'Pequeño',
    energy: 'Tranquila', purpose: 'Cría',
    tags: ['Tranquila', 'Cariñosa', 'Busca amigos'],
    purpose: 'Amigos',
    emoji: '🦮', distance: 3.7, online: false,
    bg: '#DCFCE7', location: 'Marbella',
  },
]

export const matches = [
  { id: 1, name: 'Rocky', emoji: '🐕‍🦺', breed: 'Border Collie',    distance: 2.4, online: true,  time: '10:30',      lastMsg: '¡Es un match!' },
  { id: 2, name: 'Luna',  emoji: '🐩',  breed: 'Golden Retriever', distance: 2.1, online: false, time: 'Ayer',        lastMsg: '¡Hola! Luna y Hoshi se verían genial 🐾' },
  { id: 3, name: 'Coco',  emoji: '🦮',  breed: 'Beagle',           distance: 3.7, online: false, time: 'Hace 2 días', lastMsg: '¡Es un match!' },
  { id: 4, name: 'Nina',  emoji: '🐺',  breed: 'Husky',            distance: 4.1, online: false, time: 'Hace 3 días', lastMsg: '¡Es un match!' },
]

export const places = [
  { id: 1, name: 'Clínica Veterinaria Bella Vista', type: 'Veterinaria', category: 'vet',   rating: 4.9, reviews: 214, distance: 0.8, address: 'Av. Belisario Porras, Bella Vista',      open: true,  hours: 'Abierto · cierra a las 8pm' },
  { id: 2, name: 'Parque Omar',                     type: 'Parque pet-friendly', category: 'park',  rating: 4.8, reviews: 380, distance: 1.2, address: 'Vía Porras, San Francisco',              open: true,  hours: 'Abierto · 24 horas' },
  { id: 3, name: 'PetGrooming PTY',                 type: 'Grooming',    category: 'groom', rating: 4.6, reviews: 97,  distance: 1.9, address: 'Calle 50, Marbella',                     open: true,  hours: 'Abierto · cierra a las 7pm' },
  { id: 4, name: 'Pet World Panama',                type: 'Pet Shop',    category: 'shop',  rating: 4.5, reviews: 143, distance: 2.4, address: 'Multiplaza Pacific, Punta Pacífica',     open: true,  hours: 'Abierto · cierra a las 9pm' },
  { id: 5, name: 'Hotel Pets Panama',               type: 'Hotel para mascotas', category: 'hotel', rating: 4.7, reviews: 68,  distance: 3.1, address: 'Tumba Muerto, Las Mañanitas',          open: false, hours: 'Cerrado · abre mañana a las 8am' },
  { id: 6, name: 'Veterinaria San Francisco',       type: 'Veterinaria', category: 'vet',   rating: 4.7, reviews: 189, distance: 1.5, address: 'Calle 74, San Francisco',                open: true,  hours: 'Abierto · cierra a las 6pm' },
]
export const events = [
  {
    id: 1,
    title: 'Paseo grupal en Parque Omar',
    type: 'paseo',
    emoji: '🦮',
    date: 'Sáb 14 Jun',
    time: '7:00 AM',
    location: 'Parque Omar, San Francisco',
    attendees: 12,
    maxAttendees: 20,
    joined: false,
    host: 'hoshi_oficial',
    description: 'Paseo matutino para perros de todos los tamaños. ¡Trae agua y buen humor!',
    bg: '#E0F7F4',
  },
  {
    id: 2,
    title: 'Meetup Shiba Inu Panama',
    type: 'meetup',
    emoji: '🦊',
    date: 'Dom 15 Jun',
    time: '4:00 PM',
    location: 'Costa del Este, Parque central',
    attendees: 8,
    maxAttendees: 15,
    joined: true,
    host: 'shibainu_pty',
    description: 'Encuentro exclusivo para Shibas y sus dueños. ¡Hoshi está invitada!',
    bg: '#FEE2E2',
  },
  {
    id: 3,
    title: 'Feria de Adopción PTY',
    type: 'feria',
    emoji: '❤️',
    date: 'Sáb 21 Jun',
    time: '10:00 AM',
    location: 'Multiplaza Pacific, Punta Pacífica',
    attendees: 45,
    maxAttendees: 100,
    joined: false,
    host: 'adopta_panama',
    description: 'Gran feria de adopción responsable. Más de 30 perritos buscan hogar.',
    bg: '#FCE7F3',
  },
  {
    id: 4,
    title: '🎂 Cumpleaños de Rocky',
    type: 'cumpleanos',
    emoji: '🎂',
    date: 'Vie 20 Jun',
    time: '3:00 PM',
    location: 'Calle 50, Marbella',
    attendees: 6,
    maxAttendees: 10,
    joined: false,
    host: 'rocky_bordercollie',
    description: '¡Rocky cumple 3 años! Celebración pet-friendly con pastel de carne.',
    bg: '#FEF9C3',
  },
  {
    id: 5,
    title: 'Paseo nocturno Bella Vista',
    type: 'paseo',
    emoji: '🌙',
    date: 'Mié 18 Jun',
    time: '7:00 PM',
    location: 'Av. Belisario Porras, Bella Vista',
    attendees: 5,
    maxAttendees: 12,
    joined: false,
    host: 'luna_golden',
    description: 'Paseo relajado al atardecer por Bella Vista. Ideal para perros tranquilos.',
    bg: '#EDE9FE',
  },
]
export const placeReviews = {
  1: [
    { id: 1, user: 'hoshi_oficial', emoji: '🐕', rating: 5, text: 'Excelente atención, el Dr. Mora es muy profesional y cariñoso con Hoshi.', date: 'hace 2 días' },
    { id: 2, user: 'rocky_bordercollie', emoji: '🐕‍🦺', rating: 5, text: 'Los mejores de Bella Vista, siempre puntuales y muy limpios.', date: 'hace 1 semana' },
    { id: 3, user: 'luna_golden', emoji: '🐩', rating: 4, text: 'Muy buena clínica, el único contra es que a veces hay que esperar.', date: 'hace 2 semanas' },
  ],
  2: [
    { id: 1, user: 'hoshi_oficial', emoji: '🐕', rating: 5, text: '¡El mejor parque de Panamá para perros! Siempre limpio y con mucho espacio.', date: 'hace 3 días' },
    { id: 2, user: 'rocky_bordercollie', emoji: '🐕‍🦺', rating: 5, text: 'Vamos todos los sábados, Rocky lo ama. Hay zona de agua y sombra.', date: 'hace 5 días' },
    { id: 3, user: 'luna_golden', emoji: '🐩', rating: 4, text: 'Bonito parque, los fines de semana se llena mucho pero vale la pena.', date: 'hace 1 semana' },
  ],
  3: [
    { id: 1, user: 'luna_golden', emoji: '🐩', rating: 5, text: 'Quedé hermosa después del baño 💅 El equipo es muy gentil con los perritos.', date: 'hace 1 día' },
    { id: 2, user: 'hoshi_oficial', emoji: '🐕', rating: 4, text: 'Buen servicio, Hoshi salió impecable. El precio es justo.', date: 'hace 1 semana' },
  ],
  4: [
    { id: 1, user: 'rocky_bordercollie', emoji: '🐕‍🦺', rating: 5, text: 'Tienen todo lo que necesitas para tu perro. El personal muy amable.', date: 'hace 4 días' },
    { id: 2, user: 'hoshi_oficial', emoji: '🐕', rating: 4, text: 'Buenos precios y variedad. Me gusta que tienen marcas premium.', date: 'hace 2 semanas' },
  ],
  5: [
    { id: 1, user: 'luna_golden', emoji: '🐩', rating: 5, text: 'Dejé a Luna 3 días y la cuidaron como en casa. Muy recomendado.', date: 'hace 1 semana' },
  ],
  6: [
    { id: 1, user: 'hoshi_oficial', emoji: '🐕', rating: 5, text: 'Súper cerca y muy buena atención. El Dr. es muy paciente con Hoshi.', date: 'hace 3 días' },
    { id: 2, user: 'rocky_bordercollie', emoji: '🐕‍🦺', rating: 4, text: 'Buena clínica, precios razonables y atención rápida.', date: 'hace 1 semana' },
  ],
}
export const chatMessages = {
  1: [
    { id: 1, from: 'them', text: 'Hola! 🐶 ¿Quieren juntarse este fin de semana en el Parque Omar?', time: '10:30' },
    { id: 2, from: 'me',   text: '¡Hola! Claro que sí 😍 Nos encantaría.', time: '10:32' },
    { id: 3, from: 'them', text: '¿El sábado a las 7am te parece?', time: '10:33' },
    { id: 4, from: 'me',   text: 'Perfecto, allí nos vemos 🐾', time: '10:34' },
  ],
  2: [
    { id: 1, from: 'them', text: '¡Hola! Luna y Hoshi se verían genial juntas 🐾', time: 'Ayer' },
    { id: 2, from: 'me',   text: '¡Sí! ¿Dónde sueles pasear a Luna?', time: 'Ayer' },
  ],
  3: [],
  4: [],
}